# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Runtime的使用' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod "MJExtension"

  # Pods for Runtime的使用

  target 'Runtime的使用Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Runtime的使用UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
