# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GCD使用' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GCD使用


   pod 'Masonry', '~> 1.0.2'
   pod 'AFNetworking', '~> 3.1.0'

  target 'GCD使用Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GCD使用UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
